[build]
  functions = "./functions" # where our functions are stored
  build = "yarn build" # our build command
  publish = "./build" # the directory to publish

# Rewrite url to hide ".netlify/functions"
[[redirects]]
  from = "/send"
  to = "/.netlify/functions/send"
  status = 200